physnet_kwargs = {
        'n_atom_embedding': 95,
        'n_output': 1,
        'n_dime_before_residual': 1,
        'n_dime_after_residual': 2,
        'n_output_dense': 3,
        'n_phys_atomic_res': 1,
        'n_phys_interaction_res': 1,
        'n_phys_output_res': 1,
        'n_bi_linear': 8,
        'nh_lambda': 0.01,
        'normalize': True,
        'debug_mode': False,
        'activations': 'ssp ssp ssp',
        'shared_normalize_param': True,
        'restrain_non_bond_pred': True,
        'expansion_fn': '(P_BN,P-noOut_BN):gaussian_64_10.0',
        'modules': 'P-noOut P-noOut P',
        'bonding_type': 'BN BN BN',
        'uncertainty_modify': 'none',
        'coulomb_charge_correct': False,
        'target_names': ['NMR_chemical_shift'],
        'requires_embedding': True,
        'requires_atom_prop': True,
        }